apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  # namespace: my-yolo-app
  labels:
    app: yolo
    component: back
spec:
  replicas: 2
  selector:
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        app: yolo
        component: back
    spec:
      containers:
        - name: yolo_backend
          image: kennedynjoroge/api:1
          env:
          - name: MONGO_URL
            value: mongodb://mongodb-service:27017/mydb  
          ports:
            - containerPort: 3001
     
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-api-app

  labels:
    app: yolo
    component: back
spec:
  selector:
    app: yolo
    component: back
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http     